'use strict';

const fs = require('fs');
const path = require('path');
const manifest = require('./manifest.json');
const rhythmService = require('../rhythm-game-editor/rhythm-service');

const SOURCE_FILES = [
  'game.c',
  'helpers.c',
  'highscore.c',
  'hud.c',
  'input.c',
  'note.c',
  'sound.c',
  'utils/draw_sjis.c',
];
const HEADER_FILES = [
  'game.h',
  'helpers.h',
  'highscore.h',
  'hud.h',
  'input.h',
  'note.h',
  'sound.h',
  'utils/draw_sjis.h',
];
const BOOT_FILES = [
  path.join('boot', 'sega.s'),
];

function templateRoot() {
  return path.join(__dirname, 'template');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function syncEngine(projectDir, logger) {
  const root = templateRoot();
  SOURCE_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  HEADER_FILES.forEach((name) => {
    copyFile(path.join(root, 'inc', name), path.join(projectDir, 'inc', name));
  });
  BOOT_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  ensureDir(path.join(projectDir, 'res'));
  logger?.info?.('リズムゲームエンジンをプロジェクトへ同期しました');
}

function readMainSource() {
  return fs.readFileSync(path.join(templateRoot(), 'src', 'main.c'), 'utf-8');
}

function generatedMainSource() {
  const source = readMainSource().replace(/^\/\*[\s\S]*?\*\/\s*/m, '');
  return `/* Generated by rhythm-game-builder v${manifest.version} */\n${source}`;
}

function writeMainSource(projectDir) {
  const outPath = path.join(projectDir, 'src', 'main.c');
  ensureDir(path.dirname(outPath));
  fs.writeFileSync(outPath, generatedMainSource(), 'utf-8');
}

function exportData(projectDir, assets, context = {}) {
  const validation = rhythmService.validateRhythmProject({ assets }, {
    ...context,
    projectDir,
    assets,
  });
  if (!validation.ok) {
    return {
      ok: false,
      error: `リズムゲーム設定にエラーがあります:\n${(validation.errors || []).join('\n')}`,
    };
  }
  const exported = rhythmService.exportRhythmData({
    assets,
    templateRoot: templateRoot(),
  }, {
    ...context,
    projectDir,
    assets,
    templateRoot: templateRoot(),
  });
  if (!exported.ok) return exported;
  if (validation.warnings?.length) {
    validation.warnings.forEach((warning) => context.logger?.warn?.(warning));
  }
  return exported;
}

function generateSource(_assets = [], context = {}) {
  const projectDir = context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  const assets = context.assets || _assets || [];
  try {
    syncEngine(projectDir, context.logger);
    writeMainSource(projectDir);
    const exported = exportData(projectDir, assets, context);
    if (!exported.ok) return { ok: false, error: exported.error || 'リズムゲームデータの生成に失敗しました' };
    return { ok: true, sourceCode: generatedMainSource(), exported };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildStart(payload = {}, context = {}) {
  const projectDir = payload.projectDir || context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  const assets = context.assets || [];
  try {
    syncEngine(projectDir, context.logger);
    writeMainSource(projectDir);
    const exported = exportData(projectDir, assets, context);
    if (!exported.ok) return { ok: false, error: exported.error || 'リズムゲームデータの生成に失敗しました' };
    context.logger?.info?.('リズムゲーム譜面・アセットデータをビルド前に再生成しました');
    return {
      ok: true,
      makeVariables: {
        SRC_C: ['src/main.c', ...SOURCE_FILES.map((name) => `src/${name}`), 'src/song_data.c'].join(' '),
      },
    };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildLog() {
  return { ok: true };
}

function onBuildEnd(payload, context = {}) {
  context.logger?.info?.(`リズムゲームビルド終了: ${payload?.success ? '成功' : '失敗'}`);
  return { ok: true };
}

function onBuildError(payload, context = {}) {
  context.logger?.error?.(`リズムゲームビルドエラー: ${payload?.error || 'unknown error'}`);
  return { ok: true };
}

module.exports = {
  manifest,
  generateSource,
  onBuildStart,
  onBuildLog,
  onBuildEnd,
  onBuildError,
};
