'use strict';

const fs = require('fs');
const path = require('path');
const manifest = require('./manifest.json');
const stageService = require('../block-stage-editor/stage-service');

const SOURCE_FILES = [
  'ball.c',
  'block.c',
  'gfx.c',
  'player.c',
  'powerup.c',
  'score.c',
  'snd.c',
  'ui.c',
];
const BOOT_FILES = [
  path.join('boot', 'sega.s'),
];

// Distributed build plugins must be self-contained, so this template is the
// canonical engine source used by generator/build hooks.
function templateRoot() {
  return path.join(__dirname, 'template');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function syncEngine(projectDir, logger) {
  const root = templateRoot();
  SOURCE_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  BOOT_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  copyFile(path.join(root, 'inc', 'game.h'), path.join(projectDir, 'inc', 'game.h'));
  ensureDir(path.join(projectDir, 'res'));
  logger?.info?.('ブロック崩しゲームエンジンをプロジェクトへ同期しました');
}

function readMainSource() {
  const mainPath = path.join(templateRoot(), 'src', 'main.c');
  return fs.readFileSync(mainPath, 'utf-8');
}

function generatedMainSource() {
  const source = readMainSource().replace(/^\/\*[\s\S]*?\*\/\s*/m, '');
  return `/* Generated by block-game-builder v${manifest.version} */\n${source}`;
}

function generateSource(_assets = [], context = {}) {
  const projectDir = context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    const validation = stageService.validateBlockSettings(projectDir, context.assets || _assets || []);
    if (!validation.ok) {
      return { ok: false, error: `ブロック崩しアセット設定にエラーがあります:\n${validation.errors.join('\n')}` };
    }
    syncEngine(projectDir, context.logger);
    stageService.exportStageData(projectDir, context.assets || _assets || []);
    return { ok: true, sourceCode: generatedMainSource() };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildStart(payload = {}, context = {}) {
  const projectDir = payload.projectDir || context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    const validation = stageService.validateBlockSettings(projectDir, context.assets || []);
    if (!validation.ok) {
      return { ok: false, error: `ブロック崩しアセット設定にエラーがあります:\n${validation.errors.join('\n')}` };
    }
    syncEngine(projectDir, context.logger);
    stageService.exportStageData(projectDir, context.assets || []);
    context.logger?.info?.('ブロック崩しステージデータをビルド前に再生成しました');
    return {
      ok: true,
      makeVariables: {
        SRC_C: ['src/main.c', ...SOURCE_FILES.map((name) => `src/${name}`)].join(' '),
      },
    };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildLog() {
  return { ok: true };
}

function onBuildEnd(payload, context = {}) {
  context.logger?.info?.(`ブロック崩しビルド終了: ${payload?.success ? '成功' : '失敗'}`);
  return { ok: true };
}

function onBuildError(payload, context = {}) {
  context.logger?.error?.(`ブロック崩しビルドエラー: ${payload?.error || 'unknown error'}`);
  return { ok: true };
}

module.exports = {
  manifest,
  generateSource,
  onBuildStart,
  onBuildLog,
  onBuildEnd,
  onBuildError,
};
