'use strict';

/**
 * Slideshow Plugin – index.js
 *
 * resources.res に定義された IMAGE アセット (名前が "image" で始まる) を
 * 5 秒ごとに切り替えるスライドショー用の main.c を生成する。
 *
 * BGM は名前が "bgm" のアセット (XGM2 / XGM / WAV) を自動検出してループ再生する。
 */

const manifest = require('./manifest.json');

/**
 * @param {Array<{type:string, name:string, sourcePath:string}>} assets
 * @returns {{ ok: boolean, sourceCode?: string, error?: string }}
 */
function generateSource(assets) {
  // IMAGE タイプで名前が "image" で始まるものを名前順に並べる
  const images = assets
    .filter((a) => a.type === 'IMAGE' && /^image/i.test(a.name))
    .sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));

  if (images.length === 0) {
    return {
      ok: false,
      error:
        'imageXXX という名前の IMAGE タイプのアセットが見つかりません。\n'
        + 'resources.res に IMAGE タイプのアセット（名前が "image" で始まるもの）を追加してください。',
    };
  }

  // BGM アセットを探す (名前が "bgm"、タイプ XGM2 / XGM / WAV)
  const bgmAsset = assets.find((a) => /^bgm$/i.test(a.name));
  const hasBgm = Boolean(bgmAsset);
  const isXgm = hasBgm && (bgmAsset.type === 'XGM2' || bgmAsset.type === 'XGM');
  const isWav = hasBgm && bgmAsset.type === 'WAV';

  const slideCount = images.length;
  const names = images.map((a) => a.name);

  // extern 宣言
  const externImages = names.map((n) => `extern const Image ${n};`).join('\n');
  const bgmExtern = hasBgm ? 'extern const u8 bgm[];' : '';

  // slides 配列初期化子
  const slidesInit = names.map((n) => `    &${n}`).join(',\n');

  // BGM 再生 / 停止コード
  let bgmInitCode = '';
  let bgmPlayCode = '';
  let bgmNote = '';
  if (isXgm) {
    bgmInitCode = '    XGM2_loadDriver(TRUE);';
    bgmPlayCode = '    XGM2_play(bgm);';
    bgmNote = '    /* BGM: XGM2 ループ再生 */\n';
  } else if (isWav) {
    bgmInitCode = '    XGM2_loadDriver(TRUE);';
    bgmPlayCode = '    XGM2_playPCMEx(bgm, sizeof(bgm), SOUND_PCM_CH1, 15, FALSE, TRUE);';
    bgmNote = '    /* BGM: XGM2 PCM ループ再生 */\n';
  }

  const sourceCode = `/* =============================================================
 * Slideshow Game
 * Generated by Slideshow Plugin v${manifest.version}
 * スライド数: ${slideCount}  BGM: ${hasBgm ? bgmAsset.name + ' (' + bgmAsset.type + ')' : 'なし'}
 * ============================================================= */
#include <genesis.h>
#include "resources.h"

/* ---- アセット宣言 ---- */
${externImages}
${bgmExtern ? bgmExtern + '\n' : ''}
#define SLIDE_COUNT  ${slideCount}
#define SLIDE_TIMER  (5 * 60)   /* 5秒 @ 60fps */

static const Image* const slides[SLIDE_COUNT] = {
${slidesInit}
};

/* パレット保存バッファ */
static u16 savedPal[64];

/* スライドを読み込んでパレットをキャプチャする */
static void loadSlide(u16 idx)
{
    VDP_drawImage(BG_B, slides[idx], 0, 0);
    /* VDP_drawImage がセットしたパレットを保存してから黒にする */
    PAL_getColors(0, savedPal, 64);
    PAL_setColors(0, (u16*)palette_black, 64, CPU);
}

/* ------------------------------------------------------------------ */
int main(bool hardReset)
{
    (void)hardReset;
    u16 slide   = 0;
    u16 timer   = 0;
    u16 prevBtn = 0;

    VDP_setScreenWidth320();
    PAL_setColors(0, (u16*)palette_black, 64, CPU);

  ${bgmInitCode ? bgmInitCode + '\n' : ''}
  ${bgmNote}${bgmPlayCode ? bgmPlayCode + '\n' : ''}
    /* 最初のスライドを描画してフェードイン */
    loadSlide(0);
    PAL_fadeIn(0, 63, savedPal, 20, FALSE);

    while (1)
    {
        u16 btn     = JOY_readJoypad(JOY_1);
        u16 pressed = btn & ~prevBtn;
        prevBtn     = btn;

        bool changed = FALSE;

        /* 十字キー右: 次のスライド */
        if (pressed & BUTTON_RIGHT)
        {
            slide   = (u16)((slide + 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }
        /* 十字キー左: 前のスライド */
        else if (pressed & BUTTON_LEFT)
        {
            slide   = (u16)((slide + SLIDE_COUNT - 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }

        /* 5秒経過で自動的に次のスライドへ */
        if (++timer >= SLIDE_TIMER)
        {
            slide   = (u16)((slide + 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }

        if (changed)
        {
            PAL_fadeOut(0, 63, 10, FALSE);
            VDP_clearPlane(BG_B, TRUE);
            loadSlide(slide);
            PAL_fadeIn(0, 63, savedPal, 20, FALSE);
        }

        SYS_doVBlankProcess();
    }

    return 0;
}
`;

  return { ok: true, sourceCode };
}

function migrateLegacyMainSignature(projectDir, logger) {
  if (!projectDir) return;
  const srcPath = require('path').join(projectDir, 'src', 'main.c');
  const fs = require('fs');
  if (!fs.existsSync(srcPath)) return;

  let source;
  try {
    source = fs.readFileSync(srcPath, 'utf-8');
  } catch {
    return;
  }

  // 旧版の slideshow 生成コードだけを対象にシグネチャを補正
  if (!source.includes('Generated by Slideshow Plugin')) return;

  let next = source;
  next = next.replace('int main(void)', 'int main(bool hardReset)');
  next = next.replace('bool main(bool hard)', 'int main(bool hardReset)');
  next = next.replace('bool main(bool hardReset)', 'int main(bool hardReset)');

  if (next.includes('int main(bool hardReset)') && !next.includes('(void)hardReset;')) {
    next = next.replace('int main(bool hardReset)\n{', 'int main(bool hardReset)\n{\n    (void)hardReset;');
  }

  next = next.replace('return FALSE;', 'return 0;');

  if (next === source) return;
  try {
    fs.writeFileSync(srcPath, next, 'utf-8');
    logger?.info(`legacy main signature migrated: ${srcPath}`);
  } catch {
    // ビルド自体は継続させる
  }
}

function onBuildStart(payload, context = {}) {
  migrateLegacyMainSignature(payload?.projectDir, context?.logger);
  context?.logger?.info(`build start: project=${payload?.projectDir || '-'}`);
  return {
    ok: true,
    // Slideshow is a generated single-file program. Limit SGDK's wildcard source scan
    // so old game-specific src/*.c files in the project do not break the build.
    makeVariables: {
      SRC_C: 'src/main.c',
    },
  };
}

function onBuildLog(payload, context = {}) {
  return { ok: true };
}

function onBuildEnd(payload, context = {}) {
  context?.logger?.info(`build end: success=${Boolean(payload?.success)}`);
  return { ok: true };
}

function onBuildError(payload, context = {}) {
  context?.logger?.error(`build error: ${payload?.error || 'unknown'}`);
  return { ok: true };
}

module.exports = {
  manifest,
  generateSource,
  onBuildStart,
  onBuildLog,
  onBuildEnd,
  onBuildError,
};
