'use strict';

const fs = require('fs');
const path = require('path');
const manifest = require('./manifest.json');
const dungeonService = require('../dungeon-game-editor/dungeon-service');

const SOURCE_FILES = [
  'dungeon_view.c',
];
const HEADER_FILES = [
  'dungeon_game.h',
  'dungeon_view.h',
];
const BOOT_FILES = [
  path.join('boot', 'sega.s'),
];

function templateRoot() {
  return path.join(__dirname, 'template');
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function copyFile(src, dest) {
  ensureDir(path.dirname(dest));
  fs.copyFileSync(src, dest);
}

function copyDirIfExists(src, dest) {
  if (!fs.existsSync(src)) return;
  ensureDir(dest);
  fs.readdirSync(src, { withFileTypes: true }).forEach((entry) => {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirIfExists(from, to);
    } else if (entry.isFile()) {
      copyFile(from, to);
    }
  });
}

function syncEngine(projectDir, logger) {
  const root = templateRoot();
  SOURCE_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  HEADER_FILES.forEach((name) => {
    copyFile(path.join(root, 'inc', name), path.join(projectDir, 'inc', name));
  });
  BOOT_FILES.forEach((name) => {
    copyFile(path.join(root, 'src', name), path.join(projectDir, 'src', name));
  });
  copyDirIfExists(path.join(root, 'res'), path.join(projectDir, 'res'));
  ensureDir(path.join(projectDir, 'src'));
  ensureDir(path.join(projectDir, 'inc'));
  ensureDir(path.join(projectDir, 'res'));
  logger?.info?.('ダンジョンゲームエンジンをプロジェクトへ同期しました');
}

function readMainSource() {
  return fs.readFileSync(path.join(templateRoot(), 'src', 'main.c'), 'utf-8');
}

function generatedMainSource() {
  const source = readMainSource().replace(/^\/\*[\s\S]*?\*\/\s*/m, '');
  return `/* Generated by dungeon-game-builder v${manifest.version} */\n${source}`;
}

function writeMainSource(projectDir) {
  const outPath = path.join(projectDir, 'src', 'main.c');
  ensureDir(path.dirname(outPath));
  fs.writeFileSync(outPath, generatedMainSource(), 'utf-8');
}

function exportData(projectDir, context = {}) {
  const exported = dungeonService.exportDungeonData(projectDir);
  if (!exported.ok) return exported;
  context.logger?.info?.(`ダンジョンフロアデータを生成しました (${exported.floorCount} floor)`);
  return exported;
}

function generateSource(_assets = [], context = {}) {
  const projectDir = context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    syncEngine(projectDir, context.logger);
    writeMainSource(projectDir);
    const exported = exportData(projectDir, context);
    if (!exported.ok) return { ok: false, error: exported.error || 'ダンジョンデータの生成に失敗しました' };
    return { ok: true, sourceCode: generatedMainSource(), exported };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildStart(payload = {}, context = {}) {
  const projectDir = payload.projectDir || context.projectDir;
  if (!projectDir) return { ok: false, error: 'projectDir is required' };
  try {
    syncEngine(projectDir, context.logger);
    writeMainSource(projectDir);
    const exported = exportData(projectDir, context);
    if (!exported.ok) return { ok: false, error: exported.error || 'ダンジョンデータの生成に失敗しました' };
    context.logger?.info?.('ダンジョンマップ・BGタイル描画データをビルド前に再生成しました');
    return {
      ok: true,
      makeVariables: {
        SRC_C: ['src/main.c', ...SOURCE_FILES.map((name) => `src/${name}`), 'src/dungeon_data.c', 'src/dungeon_patterns.c'].join(' '),
      },
    };
  } catch (err) {
    return { ok: false, error: String(err?.message || err) };
  }
}

function onBuildLog() {
  return { ok: true };
}

function onBuildEnd(payload, context = {}) {
  context.logger?.info?.(`ダンジョンゲームビルド終了: ${payload?.success ? '成功' : '失敗'}`);
  return { ok: true };
}

function onBuildError(payload, context = {}) {
  context.logger?.error?.(`ダンジョンゲームビルドエラー: ${payload?.error || 'unknown error'}`);
  return { ok: true };
}

module.exports = {
  manifest,
  generateSource,
  onBuildStart,
  onBuildLog,
  onBuildEnd,
  onBuildError,
};
