/* =============================================================
 * Asset Checker
 * Generated by asset-checker v{{VERSION}}
 * IMAGE: {{IMAGE_COUNT}}  SPRITE: {{SPRITE_COUNT}}  MAP/TILEMAP: {{TILEMAP_COUNT}}  BGM: {{BGM_COUNT}}
 * ============================================================= */
#include <genesis.h>
{{RESOURCE_INCLUDES}}

#define IMAGE_COUNT {{IMAGE_COUNT}}
#define SPRITE_COUNT {{SPRITE_COUNT}}
#define TILEMAP_COUNT {{TILEMAP_COUNT}}
#define BGM_COUNT {{BGM_COUNT}}
#define UI_CATEGORY_COUNT 4
#define TILE_BASE_INDEX TILE_USER_INDEX
#define TILEMAP_PLANE_W 64
#define TILEMAP_PLANE_H 32
#define TILEMAP_MAP_BLOCK_SIZE 128
#define TILEMAP_MAX_TILESETS 8
#define TILEMAP_MAX_MAP_LAYERS 8
#define TILEMAP_MAX_PALETTES 3
#define TILEMAP_VIEW_META_W 21
#define TILEMAP_VIEW_META_H 16

typedef enum
{
    CATEGORY_IMAGE = 0,
    CATEGORY_SPRITE = 1,
    CATEGORY_TILEMAP = 2,
    CATEGORY_BGM = 3
} Category;

typedef enum
{
    BGM_KIND_XGM = 0,
    BGM_KIND_XGM2 = 1,
    BGM_KIND_WAV = 2
} BgmKind;

typedef enum
{
    TILEMAP_KIND_TILEMAP = 0,
    TILEMAP_KIND_MAP = 1
} TilemapKind;

typedef struct
{
    const char* label;
    const Image* image;
} ImageEntry;

typedef struct
{
    const char* label;
    const SpriteDefinition* sprite;
} SpriteEntry;

typedef struct
{
    const char* label;
    TilemapKind kind;
    const TileMap* tilemap;
    const MapDefinition* mapDefinition;
    const MapDefinition* mapDefinitions[TILEMAP_MAX_MAP_LAYERS];
    const MapDefinition* priorityDefinitions[TILEMAP_MAX_MAP_LAYERS];
    u16 mapDefinitionCount;
    const u16* previewLayer;
    const TileSet* tilesets[TILEMAP_MAX_TILESETS];
    u16 tileOffsets[TILEMAP_MAX_TILESETS];
    u16 paletteSlots[TILEMAP_MAX_TILESETS];
    u16 tilesetCount;
    const Palette* palettes[TILEMAP_MAX_PALETTES];
    u16 paletteCount;
    u16 tileWidth;
    u16 tileHeight;
} TilemapEntry;

typedef struct
{
    const char* label;
    BgmKind kind;
    const u8* data;
    u32 size;
    bool halfRate;
} BgmEntry;

static const ImageEntry image_entries[IMAGE_COUNT > 0 ? IMAGE_COUNT : 1] = {
{{IMAGE_ENTRIES}}
};

static const SpriteEntry sprite_entries[SPRITE_COUNT > 0 ? SPRITE_COUNT : 1] = {
{{SPRITE_ENTRIES}}
};

{{TILEMAP_LAYER_DATA}}

static const TilemapEntry tilemap_entries[TILEMAP_COUNT > 0 ? TILEMAP_COUNT : 1] = {
{{TILEMAP_ENTRIES}}
};

static const BgmEntry bgm_entries[BGM_COUNT > 0 ? BGM_COUNT : 1] = {
{{BGM_ENTRIES}}
};

static Category category = CATEGORY_IMAGE;
static u16 image_index = 0;
static u16 sprite_index = 0;
static u16 tilemap_index = 0;
static u16 bgm_index = 0;
static u16 sprite_anim = 0;
static u16 tile_scroll_dir = 0;
static u16 tile_scroll_speed = 1;
static s32 tile_scroll_x = 0;
static s32 tile_scroll_y = 0;
static bool sprite_playing = TRUE;
static bool bgm_playing = TRUE;
static bool bgm_loop = TRUE;
static bool show_help = TRUE;
static BgmKind active_bgm_kind = BGM_KIND_XGM2;
static Sprite* current_sprite = NULL;
static Map* current_maps[TILEMAP_MAX_MAP_LAYERS];
static Map* current_priority_maps[TILEMAP_MAX_MAP_LAYERS];
static u16 current_map_count = 0;
static u16 tilemap_preview_buffer[TILEMAP_VIEW_META_W * TILEMAP_VIEW_META_H * 4];
static s16 tilemap_preview_meta_x = -TILEMAP_VIEW_META_W;
static s16 tilemap_preview_meta_y = 0;

static u16 count_for_category(Category cat)
{
    switch (cat)
    {
        case CATEGORY_IMAGE: return IMAGE_COUNT;
        case CATEGORY_SPRITE: return SPRITE_COUNT;
        case CATEGORY_TILEMAP: return TILEMAP_COUNT;
        case CATEGORY_BGM: return BGM_COUNT;
        default: return 0;
    }
}

static u16* index_for_category(Category cat)
{
    switch (cat)
    {
        case CATEGORY_IMAGE: return &image_index;
        case CATEGORY_SPRITE: return &sprite_index;
        case CATEGORY_TILEMAP: return &tilemap_index;
        case CATEGORY_BGM: return &bgm_index;
        default: return &image_index;
    }
}

static u16 sprite_animation_count(void)
{
    if (SPRITE_COUNT == 0) return 1;
    const SpriteDefinition* definition = sprite_entries[sprite_index].sprite;
    if (!definition || definition->numAnimation == 0) return 1;
    return definition->numAnimation;
}

static void clamp_sprite_animation(void)
{
    const u16 count = sprite_animation_count();
    if (sprite_anim >= count) sprite_anim = 0;
}

static u16 tilemap_base_attr(void)
{
    return TILE_ATTR_FULL(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX);
}

static u16 wrap_meta_coord(s16 value, u16 limit)
{
    if (limit == 0) return 0;
    s32 result = value;
    while (result < 0) result += limit;
    return (u16)(result % limit);
}

static u16 tilemap_palette_for_tile_index(const TilemapEntry* entry, u16 rawIndex, u16 encodedPalette)
{
    if (entry && entry->paletteCount > 0)
    {
        for (u16 i = 0; i < entry->tilesetCount && i < TILEMAP_MAX_TILESETS; i++)
        {
            const TileSet* tileset = entry->tilesets[i];
            const u16 base = entry->tileOffsets[i];
            const u16 tileCount = tileset ? tileset->numTile : 0;
            if (rawIndex >= base && rawIndex < (u16)(base + tileCount))
            {
                const u16 slot = entry->paletteSlots[i];
                return (u16)((slot < TILEMAP_MAX_PALETTES) ? (slot + 1) : PAL1);
            }
        }
    }

    if (encodedPalette < TILEMAP_MAX_PALETTES) return (u16)(encodedPalette + 1);
    return encodedPalette;
}

static void add_tilemap_base_attr(const TilemapEntry* entry, u16* data, u16 count)
{
    while (count--)
    {
        const u16 tile = *data;
        const u16 raw_index = tile & TILE_INDEX_MASK;
        const u16 tile_index = raw_index + TILE_BASE_INDEX;
        const u16 encodedPalette = (tile & TILE_ATTR_PALETTE_MASK) >> TILE_ATTR_PALETTE_SFT;
        const u16 palette = tilemap_palette_for_tile_index(entry, raw_index, encodedPalette);
        *data++ = (tile & ~TILE_ATTR_PALETTE_MASK & ~TILE_INDEX_MASK) | (palette << TILE_ATTR_PALETTE_SFT) | tile_index;
    }
}

static u16 tilemap_preview_value_to_attr(const TilemapEntry* entry, u16 value)
{
    const u16 gid = value & TILE_INDEX_MASK;
    if (gid == 0) return 0;
    const u16 raw_index = gid - 1;
    const u16 palette = tilemap_palette_for_tile_index(entry, raw_index, 0);
    const u16 priority = value & TILE_ATTR_PRIORITY_MASK;
    return priority | (palette << TILE_ATTR_PALETTE_SFT) | (raw_index + TILE_BASE_INDEX);
}

static void stop_bgm(void)
{
    if (BGM_COUNT > 0)
    {
        if (active_bgm_kind == BGM_KIND_XGM)
        {
            XGM_stopPlay();
        }
        else if (active_bgm_kind == BGM_KIND_WAV)
        {
            XGM2_stopPCM(SOUND_PCM_CH1);
        }
        else
        {
            XGM2_stop();
        }
    }
    bgm_playing = FALSE;
}

static void play_bgm(void)
{
    if (BGM_COUNT == 0) return;

    stop_bgm();
    const BgmEntry* entry = &bgm_entries[bgm_index];
    if (!entry->data) return;

    if (entry->kind == BGM_KIND_XGM)
    {
        XGM_startPlay(entry->data);
    }
    else if (entry->kind == BGM_KIND_WAV)
    {
        Z80_loadDriver(Z80_DRIVER_XGM2, TRUE);
        XGM2_playPCMEx(entry->data, entry->size, SOUND_PCM_CH1, 15, entry->halfRate, bgm_loop);
    }
    else
    {
        XGM2_play(entry->data);
    }
    active_bgm_kind = entry->kind;
    bgm_playing = TRUE;
}

static void clear_scene(void)
{
    VDP_setHorizontalScroll(BG_B, 0);
    VDP_setVerticalScroll(BG_B, 0);
    VDP_clearPlane(BG_A, TRUE);
    VDP_clearPlane(BG_B, TRUE);
    for (u16 i = 0; i < current_map_count && i < TILEMAP_MAX_MAP_LAYERS; i++)
    {
        if (current_maps[i])
        {
            MAP_release(current_maps[i]);
            current_maps[i] = NULL;
        }
        if (current_priority_maps[i])
        {
            MAP_release(current_priority_maps[i]);
            current_priority_maps[i] = NULL;
        }
    }
    current_map_count = 0;
    if (current_sprite)
    {
        SPR_releaseSprite(current_sprite);
        current_sprite = NULL;
        SPR_update();
    }
}

static void draw_header(void)
{
    PAL_setPalette(PAL0, palette_grey, CPU);
    VDP_setTextPalette(PAL0);
    VDP_drawText("ASSET CHECKER", 1, 0);
    VDP_drawText(category == CATEGORY_IMAGE ? ">IMAGE " : " IMAGE ", 1, 2);
    VDP_drawText(category == CATEGORY_SPRITE ? ">SPRITE" : " SPRITE", 10, 2);
    VDP_drawText(category == CATEGORY_TILEMAP ? ">MAP   " : " MAP   ", 20, 2);
    VDP_drawText(category == CATEGORY_BGM ? ">BGM" : " BGM", 31, 2);
}

static void draw_footer(void)
{
    VDP_clearTextArea(0, 23, 40, 5);
    if (show_help)
    {
        VDP_drawText("UP/DOWN category  LEFT/RIGHT asset", 1, 23);
        VDP_drawText("A play/stop  B mode  C speed", 1, 24);
    }
    else
    {
        VDP_drawText("START toggles help", 1, 24);
    }
}

static void draw_status(void)
{
    char line[40];
    VDP_clearTextArea(0, 3, 40, 5);
    switch (category)
    {
        case CATEGORY_IMAGE:
            if (IMAGE_COUNT > 0)
            {
                sprintf(line, "IMAGE %u/%u", image_index + 1, IMAGE_COUNT);
                VDP_drawText(line, 1, 4);
                VDP_drawText(image_entries[image_index].label, 1, 5);
            }
            else VDP_drawText("IMAGE none", 1, 4);
            break;
        case CATEGORY_SPRITE:
            if (SPRITE_COUNT > 0)
            {
                sprintf(line, "SPRITE %u/%u anim:%u/%u %s", sprite_index + 1, SPRITE_COUNT, sprite_anim + 1, sprite_animation_count(), sprite_playing ? "PLAY" : "STOP");
                VDP_drawText(line, 1, 4);
                VDP_drawText(sprite_entries[sprite_index].label, 1, 5);
            }
            else VDP_drawText("SPRITE none", 1, 4);
            break;
        case CATEGORY_TILEMAP:
            if (TILEMAP_COUNT > 0)
            {
                sprintf(line, "MAP %u/%u dir:%u sp:%u spr:%s", tilemap_index + 1, TILEMAP_COUNT, tile_scroll_dir, tile_scroll_speed, current_sprite ? "ON" : "-");
                VDP_drawText(line, 1, 4);
                VDP_drawText(tilemap_entries[tilemap_index].label, 1, 5);
            }
            else VDP_drawText("MAP/TILEMAP none", 1, 4);
            break;
        case CATEGORY_BGM:
            if (BGM_COUNT > 0)
            {
                sprintf(line, "BGM %u/%u %s loop:%s", bgm_index + 1, BGM_COUNT, bgm_playing ? "PLAY" : "STOP", bgm_loop ? "ON" : "OFF");
                VDP_drawText(line, 1, 4);
                VDP_drawText(bgm_entries[bgm_index].label, 1, 5);
            }
            else VDP_drawText("BGM none", 1, 4);
            break;
    }
}

static void load_image(void)
{
    clear_scene();
    if (IMAGE_COUNT > 0 && image_entries[image_index].image)
    {
        if (image_entries[image_index].image->palette && image_entries[image_index].image->palette->data)
        {
            PAL_setPalette(PAL1, image_entries[image_index].image->palette->data, CPU);
        }
        VDP_drawImageEx(
            BG_B,
            image_entries[image_index].image,
            TILE_ATTR_FULL(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX),
            0,
            0,
            FALSE,
            DMA
        );
    }
    draw_header();
    draw_status();
    draw_footer();
}

static void load_sprite(void)
{
    clear_scene();
    draw_header();
    draw_status();
    draw_footer();
    SPR_init();
    if (SPRITE_COUNT > 0 && sprite_entries[sprite_index].sprite)
    {
        clamp_sprite_animation();
        if (sprite_entries[sprite_index].sprite->palette && sprite_entries[sprite_index].sprite->palette->data)
        {
            PAL_setPalette(PAL2, sprite_entries[sprite_index].sprite->palette->data, CPU);
        }
        current_sprite = SPR_addSprite(sprite_entries[sprite_index].sprite, 144, 108, TILE_ATTR(PAL2, FALSE, FALSE, FALSE));
        if (current_sprite)
        {
            SPR_setAnimationLoop(current_sprite, sprite_playing);
            SPR_setAnim(current_sprite, sprite_anim);
        }
    }
}

static void add_tilemap_overlay_sprite(const TilemapEntry* entry)
{
    if (SPRITE_COUNT == 0 || !sprite_entries[sprite_index].sprite) return;
    if (entry && entry->paletteCount >= TILEMAP_MAX_PALETTES) return;
    clamp_sprite_animation();
    if (sprite_entries[sprite_index].sprite->palette && sprite_entries[sprite_index].sprite->palette->data)
    {
        PAL_setPalette(PAL3, sprite_entries[sprite_index].sprite->palette->data, CPU);
    }
    current_sprite = SPR_addSprite(sprite_entries[sprite_index].sprite, 144, 104, TILE_ATTR(PAL3, FALSE, FALSE, FALSE));
    if (current_sprite)
    {
        SPR_setAnimationLoop(current_sprite, sprite_playing);
        SPR_setAnim(current_sprite, sprite_anim);
    }
}

static void load_tilemap_palettes(const TilemapEntry* entry)
{
    for (u16 i = 0; i < entry->paletteCount && i < TILEMAP_MAX_PALETTES; i++)
    {
        if (entry->palettes[i] && entry->palettes[i]->data)
        {
            PAL_setPalette((u16)(PAL1 + i), entry->palettes[i]->data, CPU);
        }
    }
}

static void reset_tilemap_preview(void)
{
    tilemap_preview_meta_x = -TILEMAP_VIEW_META_W;
    tilemap_preview_meta_y = 0;
}

static u16 map_meta_width(const TilemapEntry* entry)
{
    if (entry->tileWidth > 1) return (u16)((entry->tileWidth + 1) / 2);
    if (current_map_count > 0 && current_maps[0] && current_maps[0]->w) return (u16)(current_maps[0]->w * 8);
    return 1;
}

static u16 map_meta_height(const TilemapEntry* entry)
{
    if (entry->tileHeight > 1) return (u16)((entry->tileHeight + 1) / 2);
    if (current_map_count > 0 && current_maps[0] && current_maps[0]->h) return (u16)(current_maps[0]->h * 8);
    return 1;
}

static bool tile_has_pixels(u16 tile)
{
    return (tile & TILE_INDEX_MASK) != 0;
}

static void draw_map_meta_column(const TilemapEntry* entry, s16 meta_x, s16 meta_y)
{
    if (current_map_count == 0) return;

    u16* left = tilemap_preview_buffer;
    u16* right = tilemap_preview_buffer + (TILEMAP_VIEW_META_H * 2);
    u16 tile[4];
    u16 layer_tile[4];
    u16 priority_tile[4];
    const u16 map_w = map_meta_width(entry);
    const u16 map_h = map_meta_height(entry);

    for (u16 y = 0; y < TILEMAP_VIEW_META_H; y++)
    {
        tile[0] = tile[1] = tile[2] = tile[3] = 0;
        for (u16 layer = 0; layer < current_map_count; layer++)
        {
            if (!current_maps[layer]) continue;
            MAP_getTilemapRect(current_maps[layer], wrap_meta_coord(meta_x, map_w), wrap_meta_coord((s16)(meta_y + y), map_h), 1, 1, TRUE, layer_tile);
            if (current_priority_maps[layer])
            {
                MAP_getTilemapRect(current_priority_maps[layer], wrap_meta_coord(meta_x, map_w), wrap_meta_coord((s16)(meta_y + y), map_h), 1, 1, TRUE, priority_tile);
                for (u16 i = 0; i < 4; i++)
                {
                    if (tile_has_pixels(layer_tile[i]) && tile_has_pixels(priority_tile[i])) layer_tile[i] |= TILE_ATTR_PRIORITY_MASK;
                }
            }
            for (u16 i = 0; i < 4; i++)
            {
                if (tile_has_pixels(layer_tile[i])) tile[i] = layer_tile[i];
            }
        }
        add_tilemap_base_attr(entry, tile, 4);
        left[(y * 2) + 0] = tile[0];
        left[(y * 2) + 1] = tile[1];
        right[(y * 2) + 0] = tile[2];
        right[(y * 2) + 1] = tile[3];
    }

    VDP_setTileMapDataColumnFast(BG_B, left, wrap_meta_coord((s16)(meta_x * 2), TILEMAP_PLANE_W), 0, TILEMAP_VIEW_META_H * 2, DMA_QUEUE);
    VDP_setTileMapDataColumnFast(BG_B, right, wrap_meta_coord((s16)((meta_x * 2) + 1), TILEMAP_PLANE_W), 0, TILEMAP_VIEW_META_H * 2, DMA_QUEUE);
}

static void draw_map_meta_row(const TilemapEntry* entry, s16 meta_x, s16 meta_y)
{
    if (current_map_count == 0) return;

    u16* top = tilemap_preview_buffer;
    u16* bottom = tilemap_preview_buffer + (TILEMAP_VIEW_META_W * 2);
    u16 tile[4];
    u16 layer_tile[4];
    u16 priority_tile[4];
    const u16 map_w = map_meta_width(entry);
    const u16 map_h = map_meta_height(entry);

    for (u16 x = 0; x < TILEMAP_VIEW_META_W; x++)
    {
        tile[0] = tile[1] = tile[2] = tile[3] = 0;
        for (u16 layer = 0; layer < current_map_count; layer++)
        {
            if (!current_maps[layer]) continue;
            MAP_getTilemapRect(current_maps[layer], wrap_meta_coord((s16)(meta_x + x), map_w), wrap_meta_coord(meta_y, map_h), 1, 1, FALSE, layer_tile);
            if (current_priority_maps[layer])
            {
                MAP_getTilemapRect(current_priority_maps[layer], wrap_meta_coord((s16)(meta_x + x), map_w), wrap_meta_coord(meta_y, map_h), 1, 1, FALSE, priority_tile);
                for (u16 i = 0; i < 4; i++)
                {
                    if (tile_has_pixels(layer_tile[i]) && tile_has_pixels(priority_tile[i])) layer_tile[i] |= TILE_ATTR_PRIORITY_MASK;
                }
            }
            for (u16 i = 0; i < 4; i++)
            {
                if (tile_has_pixels(layer_tile[i])) tile[i] = layer_tile[i];
            }
        }
        add_tilemap_base_attr(entry, tile, 4);
        top[(x * 2) + 0] = tile[0];
        top[(x * 2) + 1] = tile[1];
        bottom[(x * 2) + 0] = tile[2];
        bottom[(x * 2) + 1] = tile[3];
    }

    VDP_setTileMapDataRow(BG_B, top, wrap_meta_coord((s16)(meta_y * 2), TILEMAP_PLANE_H), 0, TILEMAP_VIEW_META_W * 2, DMA_QUEUE);
    VDP_setTileMapDataRow(BG_B, bottom, wrap_meta_coord((s16)((meta_y * 2) + 1), TILEMAP_PLANE_H), 0, TILEMAP_VIEW_META_W * 2, DMA_QUEUE);
}

static void redraw_map_preview(const TilemapEntry* entry, bool force)
{
    if (current_map_count == 0) return;

    const s16 target_x = (s16)(tile_scroll_x >> 4);
    const s16 target_y = (s16)(tile_scroll_y >> 4);

    if (force)
    {
        tilemap_preview_meta_x = (s16)(target_x - TILEMAP_VIEW_META_W);
        tilemap_preview_meta_y = target_y;
    }

    while (tilemap_preview_meta_x < target_x)
    {
        draw_map_meta_column(entry, (s16)(tilemap_preview_meta_x + TILEMAP_VIEW_META_W), target_y);
        tilemap_preview_meta_x++;
    }
    while (tilemap_preview_meta_x > target_x)
    {
        tilemap_preview_meta_x--;
        draw_map_meta_column(entry, tilemap_preview_meta_x, target_y);
    }
    while (tilemap_preview_meta_y < target_y)
    {
        draw_map_meta_row(entry, target_x, (s16)(tilemap_preview_meta_y + TILEMAP_VIEW_META_H));
        tilemap_preview_meta_y++;
    }
    while (tilemap_preview_meta_y > target_y)
    {
        tilemap_preview_meta_y--;
        draw_map_meta_row(entry, target_x, tilemap_preview_meta_y);
    }
}

static void draw_preview_tile_column(const TilemapEntry* entry, s16 tile_x, s16 tile_y)
{
    if (!entry->previewLayer) return;
    const u16 map_w = entry->tileWidth ? entry->tileWidth : 1;
    const u16 map_h = entry->tileHeight ? entry->tileHeight : 1;
    for (u16 y = 0; y < TILEMAP_PLANE_H; y++)
    {
        const u16 source_x = wrap_meta_coord(tile_x, map_w);
        const u16 source_y = wrap_meta_coord((s16)(tile_y + y), map_h);
        tilemap_preview_buffer[y] = tilemap_preview_value_to_attr(entry, entry->previewLayer[(source_y * map_w) + source_x]);
    }
    VDP_setTileMapDataColumnFast(BG_B, tilemap_preview_buffer, wrap_meta_coord(tile_x, TILEMAP_PLANE_W), 0, TILEMAP_PLANE_H, DMA_QUEUE);
}

static void draw_preview_tile_row(const TilemapEntry* entry, s16 tile_x, s16 tile_y)
{
    if (!entry->previewLayer) return;
    const u16 map_w = entry->tileWidth ? entry->tileWidth : 1;
    const u16 map_h = entry->tileHeight ? entry->tileHeight : 1;
    for (u16 x = 0; x < TILEMAP_PLANE_W; x++)
    {
        const u16 source_x = wrap_meta_coord((s16)(tile_x + x), map_w);
        const u16 source_y = wrap_meta_coord(tile_y, map_h);
        tilemap_preview_buffer[x] = tilemap_preview_value_to_attr(entry, entry->previewLayer[(source_y * map_w) + source_x]);
    }
    VDP_setTileMapDataRow(BG_B, tilemap_preview_buffer, wrap_meta_coord(tile_y, TILEMAP_PLANE_H), 0, TILEMAP_PLANE_W, DMA_QUEUE);
}

static void redraw_preview_layer(const TilemapEntry* entry, bool force)
{
    if (!entry->previewLayer) return;

    const s16 target_x = (s16)(tile_scroll_x >> 3);
    const s16 target_y = (s16)(tile_scroll_y >> 3);

    if (force)
    {
        tilemap_preview_meta_x = (s16)(target_x - TILEMAP_PLANE_W);
        tilemap_preview_meta_y = target_y;
    }

    while (tilemap_preview_meta_x < target_x)
    {
        draw_preview_tile_column(entry, (s16)(tilemap_preview_meta_x + TILEMAP_PLANE_W), target_y);
        tilemap_preview_meta_x++;
    }
    while (tilemap_preview_meta_x > target_x)
    {
        tilemap_preview_meta_x--;
        draw_preview_tile_column(entry, tilemap_preview_meta_x, target_y);
    }
    while (tilemap_preview_meta_y < target_y)
    {
        draw_preview_tile_row(entry, target_x, (s16)(tilemap_preview_meta_y + TILEMAP_PLANE_H));
        tilemap_preview_meta_y++;
    }
    while (tilemap_preview_meta_y > target_y)
    {
        tilemap_preview_meta_y--;
        draw_preview_tile_row(entry, target_x, tilemap_preview_meta_y);
    }
}

static void apply_map_preview_scroll(void)
{
    VDP_setHorizontalScrollVSync(BG_B, -(s16)tile_scroll_x);
    VDP_setVerticalScrollVSync(BG_B, (s16)tile_scroll_y);
}

static void draw_repeated_tilemap(const TilemapEntry* entry)
{
    const u16 tile_w = entry->tilemap->w ? entry->tilemap->w : 1;
    const u16 tile_h = entry->tilemap->h ? entry->tilemap->h : 1;
    const u16 attr = tilemap_base_attr();

    for (u16 y = 0; y < TILEMAP_PLANE_H; y += tile_h)
    {
        const u16 draw_h = (y + tile_h > TILEMAP_PLANE_H) ? (TILEMAP_PLANE_H - y) : tile_h;
        for (u16 x = 0; x < TILEMAP_PLANE_W; x += tile_w)
        {
            const u16 draw_w = (x + tile_w > TILEMAP_PLANE_W) ? (TILEMAP_PLANE_W - x) : tile_w;
            VDP_setTileMapEx(BG_B, entry->tilemap, attr, x, y, 0, 0, draw_w, draw_h, CPU);
        }
    }
}

static void load_tilemap(void)
{
    clear_scene();
    draw_header();
    draw_status();
    draw_footer();
    tile_scroll_x = 0;
    tile_scroll_y = 0;
    reset_tilemap_preview();

    if (TILEMAP_COUNT > 0 && tilemap_entries[tilemap_index].tilesetCount > 0)
    {
        const TilemapEntry* entry = &tilemap_entries[tilemap_index];
        load_tilemap_palettes(entry);
        for (u16 i = 0; (i < entry->tilesetCount) && (i < TILEMAP_MAX_TILESETS); i++)
        {
            if (entry->tilesets[i])
            {
                VDP_loadTileSet(entry->tilesets[i], (u16)(TILE_BASE_INDEX + entry->tileOffsets[i]), DMA);
            }
        }
        if (entry->previewLayer)
        {
            redraw_preview_layer(entry, TRUE);
            apply_map_preview_scroll();
        }
        else if (entry->kind == TILEMAP_KIND_MAP && (entry->mapDefinition || entry->mapDefinitionCount > 0))
        {
            if (entry->mapDefinitionCount > 0)
            {
                for (u16 i = 0; i < entry->mapDefinitionCount && i < TILEMAP_MAX_MAP_LAYERS; i++)
                {
                        if (entry->mapDefinitions[i])
                        {
                            current_maps[current_map_count] = MAP_create(entry->mapDefinitions[i], BG_B, 0);
                            if (current_maps[current_map_count])
                            {
                                if (entry->priorityDefinitions[i])
                                {
                                    current_priority_maps[current_map_count] = MAP_create(entry->priorityDefinitions[i], BG_B, 0);
                                }
                                current_map_count++;
                            }
                        }
                }
            }
            else if (entry->mapDefinition)
            {
                current_maps[0] = MAP_create(entry->mapDefinition, BG_B, 0);
                current_map_count = current_maps[0] ? 1 : 0;
            }
            if (current_map_count > 0)
            {
                redraw_map_preview(entry, TRUE);
                apply_map_preview_scroll();
            }
        }
        else if (entry->tilemap)
        {
            draw_repeated_tilemap(entry);
        }
        add_tilemap_overlay_sprite(entry);
    }
    else if (TILEMAP_COUNT > 0)
    {
        VDP_drawText("MAP/TILEMAP needs tileset", 1, 10);
    }
}

static void load_bgm_status(void)
{
    clear_scene();
    if (bgm_playing && BGM_COUNT > 0) play_bgm();
    draw_header();
    draw_status();
    draw_footer();
}

static void refresh_category(void)
{
    switch (category)
    {
        case CATEGORY_IMAGE: load_image(); break;
        case CATEGORY_SPRITE: load_sprite(); break;
        case CATEGORY_TILEMAP: load_tilemap(); break;
        case CATEGORY_BGM: load_bgm_status(); break;
    }
}

static void move_selection(s16 delta)
{
    u16 count = count_for_category(category);
    u16* index = index_for_category(category);
    if (count == 0) return;
    if (delta > 0) *index = (u16)((*index + 1) % count);
    else *index = (u16)((*index + count - 1) % count);
    if (category == CATEGORY_SPRITE) sprite_anim = 0;
    if (category == CATEGORY_BGM && bgm_playing) play_bgm();
    refresh_category();
}

static void handle_a(void)
{
    if (category == CATEGORY_SPRITE && current_sprite)
    {
        sprite_playing = !sprite_playing;
        SPR_setAnimationLoop(current_sprite, sprite_playing);
        draw_status();
    }
    else if (category == CATEGORY_TILEMAP && current_sprite)
    {
        sprite_playing = !sprite_playing;
        SPR_setAnimationLoop(current_sprite, sprite_playing);
        draw_status();
    }
    else if (category == CATEGORY_BGM && BGM_COUNT > 0)
    {
        if (bgm_playing) stop_bgm();
        else play_bgm();
        draw_status();
    }
}

static void handle_b(void)
{
    if (category == CATEGORY_SPRITE && current_sprite)
    {
        sprite_anim = (u16)((sprite_anim + 1) % sprite_animation_count());
        SPR_setAnim(current_sprite, sprite_anim);
        draw_status();
    }
    else if (category == CATEGORY_TILEMAP)
    {
        tile_scroll_dir = (u16)((tile_scroll_dir + 1) % 4);
        draw_status();
    }
    else if (category == CATEGORY_BGM)
    {
        bgm_loop = !bgm_loop;
        if (bgm_playing && BGM_COUNT > 0) play_bgm();
        draw_status();
    }
}

static void handle_c(void)
{
    if (category == CATEGORY_TILEMAP)
    {
        tile_scroll_speed = (tile_scroll_speed == 1) ? 2 : (tile_scroll_speed == 2) ? 4 : 1;
        draw_status();
    }
}

static void update_tilemap_scroll(void)
{
    if (category != CATEGORY_TILEMAP || TILEMAP_COUNT == 0) return;
    const TilemapEntry* entry = &tilemap_entries[tilemap_index];
    if (entry->tilesetCount == 0) return;

    switch (tile_scroll_dir)
    {
        case 0: tile_scroll_x -= tile_scroll_speed; break;
        case 1: tile_scroll_x += tile_scroll_speed; break;
        case 2: tile_scroll_y -= tile_scroll_speed; break;
        case 3: tile_scroll_y += tile_scroll_speed; break;
    }
    if (entry->previewLayer)
    {
        redraw_preview_layer(entry, FALSE);
        apply_map_preview_scroll();
    }
    else if (entry->kind == TILEMAP_KIND_MAP)
    {
            if (current_map_count > 0)
            {
                redraw_map_preview(entry, FALSE);
                apply_map_preview_scroll();
        }
    }
    else if (entry->tilemap)
    {
        VDP_setHorizontalScroll(BG_B, -(s16)tile_scroll_x);
        VDP_setVerticalScroll(BG_B, (s16)tile_scroll_y);
    }
}

int main(bool hardReset)
{
    (void)hardReset;
    u16 prev = 0;

    VDP_setScreenWidth320();
    VDP_setPlaneSize(64, 32, TRUE);
    VDP_setScrollingMode(HSCROLL_PLANE, VSCROLL_PLANE);
    SPR_init();

    refresh_category();

    while (1)
    {
        u16 joy = JOY_readJoypad(JOY_1);
        u16 pressed = joy & ~prev;
        prev = joy;

        if (pressed & BUTTON_UP)
        {
            category = (Category)((category + UI_CATEGORY_COUNT - 1) % UI_CATEGORY_COUNT);
            refresh_category();
        }
        if (pressed & BUTTON_DOWN)
        {
            category = (Category)((category + 1) % UI_CATEGORY_COUNT);
            refresh_category();
        }
        if (pressed & BUTTON_LEFT) move_selection(-1);
        if (pressed & BUTTON_RIGHT) move_selection(1);
        if (pressed & BUTTON_A) handle_a();
        if (pressed & BUTTON_B) handle_b();
        if (pressed & BUTTON_C) handle_c();
        if (pressed & BUTTON_START)
        {
            show_help = !show_help;
            draw_footer();
        }

        update_tilemap_scroll();
        if (current_sprite) SPR_update();
        SYS_doVBlankProcess();
    }

    return 0;
}
