/* Generated by tilemap-editor. */
#ifndef TILEMAP_COLLISION_H
#define TILEMAP_COLLISION_H

#include <genesis.h>

#define TILEMAP_COLLISION_NONE 0
#define TILEMAP_COLLISION_SOLID 1
#define TILEMAP_COLLISION_PLATFORM 2
#define TILEMAP_COLLISION_LADDER 3
#define TILEMAP_COLLISION_DAMAGE 4
#define TILEMAP_COLLISION_MAP_COUNT 0

typedef struct
{
    const char* name;
    u16 width;
    u16 height;
    const u8* data;
} TilemapCollisionMap;


extern const TilemapCollisionMap* const tilemap_collision_maps[TILEMAP_COLLISION_MAP_COUNT > 0 ? TILEMAP_COLLISION_MAP_COUNT : 1];

u8 tilemap_collision_at(const TilemapCollisionMap* map, s16 tileX, s16 tileY);
const TilemapCollisionMap* tilemap_collision_find(const char* name);

#endif /* TILEMAP_COLLISION_H */
