// sonic.png
SPRITE sonic sprite/sonic.png 6 6 NONE [[0][1,1][2,2,2,2,2,2][1,1,1,1][1,1][1,1,1,1,1,1][1,1,1,1,1,1][1,1,1,1,1,1]] NONE BALANCED FAST FALSE
// Generated by tilemap-editor
TILESET bga tilesets/bga.tsx NONE NONE ROW FALSE
// Palette for bga
PALETTE bga_palette tilesets/bga.png
// Generated by tilemap-editor
TILESET enemies tilesets/enemies.tsx NONE NONE ROW FALSE
// Palette for enemies
PALETTE enemies_palette tilesets/enemies.png
// Generated by tilemap-editor
MAP map001_layer_2 maps/map001.tmx "Layer 2" NONE NONE 0 ROW
// Generated by tilemap-editor
MAP map001_layer_3 maps/map001.tmx Layer_3 NONE NONE 0 ROW
