/* Generated by tilemap-editor. */
#include <string.h>
#include "tilemap_collision.h"


const TilemapCollisionMap* const tilemap_collision_maps[TILEMAP_COLLISION_MAP_COUNT > 0 ? TILEMAP_COLLISION_MAP_COUNT : 1] = {
    NULL
};

u8 tilemap_collision_at(const TilemapCollisionMap* map, s16 tileX, s16 tileY)
{
    if (!map || !map->data || tileX < 0 || tileY < 0) return TILEMAP_COLLISION_NONE;
    if ((u16)tileX >= map->width || (u16)tileY >= map->height) return TILEMAP_COLLISION_NONE;
    return map->data[((u16)tileY * map->width) + (u16)tileX];
}

const TilemapCollisionMap* tilemap_collision_find(const char* name)
{
    if (!name) return NULL;
    for (u16 i = 0; i < TILEMAP_COLLISION_MAP_COUNT; i++)
    {
        const TilemapCollisionMap* map = tilemap_collision_maps[i];
        if (map && map->name && strcmp(map->name, name) == 0) return map;
    }
    return NULL;
}
