/* =============================================================
 * Slideshow Game
 * Generated by Slideshow Plugin v1.1.0
 * スライド数: 10  BGM: bgm (WAV)
 * ============================================================= */
#include <genesis.h>
#include "resources.h"

/* ---- アセット宣言 ---- */
extern const Image image001;
extern const Image image002;
extern const Image image003;
extern const Image image004;
extern const Image image005;
extern const Image image006;
extern const Image image007;
extern const Image image008;
extern const Image image009;
extern const Image image010;
extern const u8 bgm[];

#define SLIDE_COUNT  10
#define SLIDE_TIMER  (5 * 60)   /* 5秒 @ 60fps */

static const Image* const slides[SLIDE_COUNT] = {
    &image001,
    &image002,
    &image003,
    &image004,
    &image005,
    &image006,
    &image007,
    &image008,
    &image009,
    &image010
};

/* パレット保存バッファ */
static u16 savedPal[64];

/* スライドを読み込んでパレットをキャプチャする */
static void loadSlide(u16 idx)
{
    VDP_drawImage(BG_B, slides[idx], 0, 0);
    /* VDP_drawImage がセットしたパレットを保存してから黒にする */
    PAL_getColors(0, savedPal, 64);
    PAL_setColors(0, (u16*)palette_black, 64, CPU);
}

/* ------------------------------------------------------------------ */
int main(void)
{
    u16 slide   = 0;
    u16 timer   = 0;
    u16 prevBtn = 0;

    VDP_setScreenWidth320();
    PAL_setColors(0, (u16*)palette_black, 64, CPU);

      XGM2_loadDriver(TRUE);

      /* BGM: XGM2 PCM ループ再生 */
    XGM2_playPCMEx(bgm, sizeof(bgm), SOUND_PCM_CH1, 15, FALSE, TRUE);

    /* 最初のスライドを描画してフェードイン */
    loadSlide(0);
    PAL_fadeIn(0, 63, savedPal, 20, FALSE);

    while (1)
    {
        u16 btn     = JOY_readJoypad(JOY_1);
        u16 pressed = btn & ~prevBtn;
        prevBtn     = btn;

        bool changed = FALSE;

        /* 十字キー右: 次のスライド */
        if (pressed & BUTTON_RIGHT)
        {
            slide   = (u16)((slide + 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }
        /* 十字キー左: 前のスライド */
        else if (pressed & BUTTON_LEFT)
        {
            slide   = (u16)((slide + SLIDE_COUNT - 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }

        /* 5秒経過で自動的に次のスライドへ */
        if (++timer >= SLIDE_TIMER)
        {
            slide   = (u16)((slide + 1) % SLIDE_COUNT);
            timer   = 0;
            changed = TRUE;
        }

        if (changed)
        {
            PAL_fadeOut(0, 63, 10, FALSE);
            VDP_clearPlane(BG_B, TRUE);
            loadSlide(slide);
            PAL_fadeIn(0, 63, savedPal, 20, FALSE);
        }

        SYS_doVBlankProcess();
    }

    return 0;
}
