'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');
const { loadWithMockedElectron } = require('./helpers/mock-electron');

const assetChecker = require(path.join(__dirname, '..', 'plugins', 'asset-checker', 'index.js'));

function sampleAssets() {
  return [
    { type: 'IMAGE', name: 'img_title', sourcePath: 'gfx/title.png' },
    { type: 'SPRITE', name: 'spr_hero', sourcePath: 'sprite/hero.png', width: '4', height: '4' },
    { type: 'TILESET', name: 'tiles_stage', sourcePath: 'tiles/stage.png' },
    { type: 'PALETTE', name: 'tiles_stage_palette', sourcePath: 'tiles/stage.png' },
    { type: 'TILEMAP', name: 'map_stage', sourcePath: 'maps/stage.tmx', tileset: 'tiles_stage' },
    { type: 'XGM2', name: 'bgm_stage', sourcePath: 'music/stage.vgm' },
    { type: 'XGM', name: 'bgm_legacy', sourcePath: 'music/legacy.xgm' },
    { type: 'WAV', name: 'bgm_pcm', sourcePath: 'bgm/pcm.wav', outRate: '6650' },
    { type: 'WAV', name: 'se_hit', sourcePath: 'sfx/hit.wav' },
  ];
}

test('asset-checker declares a builder role', () => {
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'md-editor-asset-checker-plugin-test-'));
  const pluginManager = loadWithMockedElectron(path.join(__dirname, '..', 'plugin-manager.js'), { userData });
  const plugin = pluginManager.listPlugins().find((item) => item.id === 'asset-checker');

  assert.ok(plugin);
  assert.equal(plugin.name, 'アセットチェッカー');
  assert.equal(plugin.roles.length, 1);
  assert.equal(plugin.roles[0].id, 'builder');
  assert.deepEqual(plugin.pluginTypes, ['build']);
});

test('asset-checker groups supported assets and filters non-BGM wav files', () => {
  const grouped = assetChecker.collectAssets(sampleAssets());

  assert.deepEqual(grouped.images.map((entry) => entry.name), ['img_title']);
  assert.deepEqual(grouped.sprites.map((entry) => entry.name), ['spr_hero']);
  assert.deepEqual(grouped.tilemaps.map((entry) => entry.name), ['map_stage']);
  assert.deepEqual(grouped.bgms.map((entry) => entry.name), ['bgm_legacy', 'bgm_pcm', 'bgm_stage']);
  assert.equal(grouped.bgms.some((entry) => entry.name === 'se_hit'), false);
});

test('asset-checker generator renders a SGDK 2.11 single-file checker', () => {
  const result = assetChecker.generateSource(sampleAssets());

  assert.equal(result.ok, true);
  assert.match(result.sourceCode, /Generated by asset-checker v0\.1\.0/);
  assert.match(result.sourceCode, /#define IMAGE_COUNT 1/);
  assert.match(result.sourceCode, /#define SPRITE_COUNT 1/);
  assert.match(result.sourceCode, /#define TILEMAP_COUNT 1/);
  assert.match(result.sourceCode, /#define BGM_COUNT 3/);
  assert.match(result.sourceCode, /int main\(bool hardReset\)/);
  assert.match(result.sourceCode, /static u16 tile_scroll_speed = 1;/);
  assert.match(result.sourceCode, /static bool sprite_playing = TRUE;/);
  assert.match(result.sourceCode, /static bool bgm_playing = TRUE;/);
  assert.match(result.sourceCode, /sprite_animation_count\(void\)/);
  assert.match(result.sourceCode, /definition->numAnimation/);
  assert.match(result.sourceCode, /clamp_sprite_animation\(\);/);
  assert.match(result.sourceCode, /sprite_anim = \(u16\)\(\(sprite_anim \+ 1\) % sprite_animation_count\(\)\)/);
  assert.match(result.sourceCode, /VDP_drawImageEx\(/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL0, palette_grey, CPU\)/);
  assert.match(result.sourceCode, /VDP_setTextPalette\(PAL0\)/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL1, image_entries\[image_index\]\.image->palette->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR_FULL\(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX\)/);
  assert.match(result.sourceCode, /,\s*0,\s*0,\s*FALSE,\s*DMA\s*\)/);
  assert.match(result.sourceCode, /SPR_addSprite/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL2, sprite_entries\[sprite_index\]\.sprite->palette->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR\(PAL2, FALSE, FALSE, FALSE\)/);
  assert.match(result.sourceCode, /SPR_setAnim/);
  assert.match(result.sourceCode, /VDP_setTileMapEx/);
  assert.match(result.sourceCode, /PAL_setPalette\(PAL3, tilemap_entries\[tilemap_index\]\.palette->data, CPU\)/);
  assert.match(result.sourceCode, /TILE_ATTR_FULL\(PAL3, FALSE, FALSE, FALSE, TILE_BASE_INDEX\)/);
  assert.match(result.sourceCode, /\{ "map_stage", &map_stage, &tiles_stage, &tiles_stage_palette \}/);
  assert.match(result.sourceCode, /XGM2_play\(entry->data\)/);
  assert.doesNotMatch(result.sourceCode, /XGM2_loadDriver\(TRUE\)/);
  assert.match(result.sourceCode, /Z80_loadDriver\(Z80_DRIVER_XGM2, TRUE\)/);
  assert.match(result.sourceCode, /XGM2_playPCMEx\(entry->data, entry->size, SOUND_PCM_CH1, 15, entry->halfRate, bgm_loop\)/);
  assert.match(result.sourceCode, /active_bgm_kind = entry->kind/);
  assert.match(result.sourceCode, /load_bgm_status[\s\S]*if \(bgm_playing && BGM_COUNT > 0\) play_bgm\(\);/);
  assert.doesNotMatch(result.sourceCode, /se_hit/);
});

test('asset-checker accepts empty categories but rejects empty projects', () => {
  const imageOnly = assetChecker.generateSource([
    { type: 'IMAGE', name: 'img_only', sourcePath: 'gfx/only.png' },
  ]);
  const empty = assetChecker.generateSource([]);

  assert.equal(imageOnly.ok, true);
  assert.match(imageOnly.sourceCode, /#define SPRITE_COUNT 0/);
  assert.match(imageOnly.sourceCode, /\{ "none", NULL \}/);
  assert.equal(empty.ok, false);
  assert.match(empty.error, /アセットが見つかりません/);
});

test('asset-checker build hook limits SGDK source scan to generated main.c', () => {
  const messages = [];
  const result = assetChecker.onBuildStart(
    { projectDir: 'project' },
    { logger: { info: (message) => messages.push(message) } },
  );

  assert.equal(result.ok, true);
  assert.deepEqual(result.makeVariables, { SRC_C: 'src/main.c' });
  assert.match(messages[0], /asset-checker build start/);
});
