/* =============================================================
 * Asset Checker
 * Generated by asset-checker v0.1.0
 * IMAGE: 10  SPRITE: 12  TILEMAP: 0  BGM: 7
 * ============================================================= */
#include <genesis.h>
#include "resources.h"

#define IMAGE_COUNT 10
#define SPRITE_COUNT 12
#define TILEMAP_COUNT 0
#define BGM_COUNT 7
#define UI_CATEGORY_COUNT 4
#define TILE_BASE_INDEX TILE_USER_INDEX

typedef enum
{
    CATEGORY_IMAGE = 0,
    CATEGORY_SPRITE = 1,
    CATEGORY_TILEMAP = 2,
    CATEGORY_BGM = 3
} Category;

typedef enum
{
    BGM_KIND_XGM = 0,
    BGM_KIND_XGM2 = 1,
    BGM_KIND_WAV = 2
} BgmKind;

typedef struct
{
    const char* label;
    const Image* image;
} ImageEntry;

typedef struct
{
    const char* label;
    const SpriteDefinition* sprite;
} SpriteEntry;

typedef struct
{
    const char* label;
    const TileMap* tilemap;
    const TileSet* tileset;
    const Palette* palette;
} TilemapEntry;

typedef struct
{
    const char* label;
    BgmKind kind;
    const u8* data;
    u32 size;
    bool halfRate;
} BgmEntry;

static const ImageEntry image_entries[IMAGE_COUNT > 0 ? IMAGE_COUNT : 1] = {
    { "img_game_clear_screen", &img_game_clear_screen },
    { "img_game_over_screen", &img_game_over_screen },
    { "img_high_score_screen", &img_high_score_screen },
    { "img_logo_screen_1", &img_logo_screen_1 },
    { "img_logo_screen_2", &img_logo_screen_2 },
    { "img_title_screen", &img_title_screen },
    { "stage_bg_stage1", &stage_bg_stage1 },
    { "stage_bg_stage2", &stage_bg_stage2 },
    { "stage_bg_stage3", &stage_bg_stage3 },
    { "stage_bg_stage4", &stage_bg_stage4 }
};

static const SpriteEntry sprite_entries[SPRITE_COUNT > 0 ? SPRITE_COUNT : 1] = {
    { "enemies", &enemies },
    { "spr_ball", &spr_ball },
    { "spr_block_blue", &spr_block_blue },
    { "spr_block_gray", &spr_block_gray },
    { "spr_block_green", &spr_block_green },
    { "spr_block_white", &spr_block_white },
    { "spr_block_yellow", &spr_block_yellow },
    { "spr_paddle", &spr_paddle },
    { "spr_powerup_barrier", &spr_powerup_barrier },
    { "spr_powerup_multi_ball", &spr_powerup_multi_ball },
    { "spr_powerup_speed_up", &spr_powerup_speed_up },
    { "spr_powerup_strong", &spr_powerup_strong }
};

static const TilemapEntry tilemap_entries[TILEMAP_COUNT > 0 ? TILEMAP_COUNT : 1] = {
    { "none", NULL, NULL, NULL }
};

static const BgmEntry bgm_entries[BGM_COUNT > 0 ? BGM_COUNT : 1] = {
    { "bgm_001 (WAV)", BGM_KIND_WAV, bgm_001, sizeof(bgm_001), TRUE },
    { "bgm_002 (WAV)", BGM_KIND_WAV, bgm_002, sizeof(bgm_002), TRUE },
    { "bgm_003 (WAV)", BGM_KIND_WAV, bgm_003, sizeof(bgm_003), TRUE },
    { "bgm_004 (WAV)", BGM_KIND_WAV, bgm_004, sizeof(bgm_004), TRUE },
    { "bgm_19 (XGM2)", BGM_KIND_XGM2, bgm_19, sizeof(bgm_19), FALSE },
    { "bgm_27 (XGM2)", BGM_KIND_XGM2, bgm_27, sizeof(bgm_27), FALSE },
    { "bgm_vgm (XGM2)", BGM_KIND_XGM2, bgm_vgm, sizeof(bgm_vgm), FALSE }
};

static Category category = CATEGORY_IMAGE;
static u16 image_index = 0;
static u16 sprite_index = 0;
static u16 tilemap_index = 0;
static u16 bgm_index = 0;
static u16 sprite_anim = 0;
static u16 tile_scroll_dir = 0;
static u16 tile_scroll_speed = 1;
static s16 tile_scroll_x = 0;
static s16 tile_scroll_y = 0;
static bool sprite_playing = TRUE;
static bool bgm_playing = TRUE;
static bool bgm_loop = TRUE;
static bool show_help = TRUE;
static BgmKind active_bgm_kind = BGM_KIND_XGM2;
static Sprite* current_sprite = NULL;

static u16 count_for_category(Category cat)
{
    switch (cat)
    {
        case CATEGORY_IMAGE: return IMAGE_COUNT;
        case CATEGORY_SPRITE: return SPRITE_COUNT;
        case CATEGORY_TILEMAP: return TILEMAP_COUNT;
        case CATEGORY_BGM: return BGM_COUNT;
        default: return 0;
    }
}

static u16* index_for_category(Category cat)
{
    switch (cat)
    {
        case CATEGORY_IMAGE: return &image_index;
        case CATEGORY_SPRITE: return &sprite_index;
        case CATEGORY_TILEMAP: return &tilemap_index;
        case CATEGORY_BGM: return &bgm_index;
        default: return &image_index;
    }
}

static u16 sprite_animation_count(void)
{
    if (SPRITE_COUNT == 0) return 1;
    const SpriteDefinition* definition = sprite_entries[sprite_index].sprite;
    if (!definition || definition->numAnimation == 0) return 1;
    return definition->numAnimation;
}

static void clamp_sprite_animation(void)
{
    const u16 count = sprite_animation_count();
    if (sprite_anim >= count) sprite_anim = 0;
}

static void stop_bgm(void)
{
    if (BGM_COUNT > 0)
    {
        if (active_bgm_kind == BGM_KIND_XGM)
        {
            XGM_stopPlay();
        }
        else if (active_bgm_kind == BGM_KIND_WAV)
        {
            XGM2_stopPCM(SOUND_PCM_CH1);
        }
        else
        {
            XGM2_stop();
        }
    }
    bgm_playing = FALSE;
}

static void play_bgm(void)
{
    if (BGM_COUNT == 0) return;

    stop_bgm();
    const BgmEntry* entry = &bgm_entries[bgm_index];
    if (!entry->data) return;

    if (entry->kind == BGM_KIND_XGM)
    {
        XGM_startPlay(entry->data);
    }
    else if (entry->kind == BGM_KIND_WAV)
    {
        Z80_loadDriver(Z80_DRIVER_XGM2, TRUE);
        XGM2_playPCMEx(entry->data, entry->size, SOUND_PCM_CH1, 15, entry->halfRate, bgm_loop);
    }
    else
    {
        XGM2_play(entry->data);
    }
    active_bgm_kind = entry->kind;
    bgm_playing = TRUE;
}

static void clear_scene(void)
{
    VDP_setHorizontalScroll(BG_B, 0);
    VDP_setVerticalScroll(BG_B, 0);
    VDP_clearPlane(BG_A, TRUE);
    VDP_clearPlane(BG_B, TRUE);
    if (current_sprite)
    {
        SPR_releaseSprite(current_sprite);
        current_sprite = NULL;
        SPR_update();
    }
}

static void draw_header(void)
{
    PAL_setPalette(PAL0, palette_grey, CPU);
    VDP_setTextPalette(PAL0);
    VDP_drawText("ASSET CHECKER", 1, 0);
    VDP_drawText(category == CATEGORY_IMAGE ? ">IMAGE " : " IMAGE ", 1, 2);
    VDP_drawText(category == CATEGORY_SPRITE ? ">SPRITE" : " SPRITE", 10, 2);
    VDP_drawText(category == CATEGORY_TILEMAP ? ">TILEMAP" : " TILEMAP", 20, 2);
    VDP_drawText(category == CATEGORY_BGM ? ">BGM" : " BGM", 31, 2);
}

static void draw_footer(void)
{
    VDP_clearTextArea(0, 23, 40, 5);
    if (show_help)
    {
        VDP_drawText("UP/DOWN category  LEFT/RIGHT asset", 1, 23);
        VDP_drawText("A play/stop  B mode  C speed  START", 1, 24);
    }
    else
    {
        VDP_drawText("START toggles help", 1, 24);
    }
}

static void draw_status(void)
{
    char line[40];
    VDP_clearTextArea(0, 3, 40, 5);
    switch (category)
    {
        case CATEGORY_IMAGE:
            if (IMAGE_COUNT > 0)
            {
                sprintf(line, "IMAGE %u/%u", image_index + 1, IMAGE_COUNT);
                VDP_drawText(line, 1, 4);
                VDP_drawText(image_entries[image_index].label, 1, 5);
            }
            else VDP_drawText("IMAGE none", 1, 4);
            break;
        case CATEGORY_SPRITE:
            if (SPRITE_COUNT > 0)
            {
                sprintf(line, "SPRITE %u/%u anim:%u/%u %s", sprite_index + 1, SPRITE_COUNT, sprite_anim + 1, sprite_animation_count(), sprite_playing ? "PLAY" : "STOP");
                VDP_drawText(line, 1, 4);
                VDP_drawText(sprite_entries[sprite_index].label, 1, 5);
            }
            else VDP_drawText("SPRITE none", 1, 4);
            break;
        case CATEGORY_TILEMAP:
            if (TILEMAP_COUNT > 0)
            {
                sprintf(line, "TILEMAP %u/%u dir:%u speed:%u", tilemap_index + 1, TILEMAP_COUNT, tile_scroll_dir, tile_scroll_speed);
                VDP_drawText(line, 1, 4);
                VDP_drawText(tilemap_entries[tilemap_index].label, 1, 5);
            }
            else VDP_drawText("TILEMAP none", 1, 4);
            break;
        case CATEGORY_BGM:
            if (BGM_COUNT > 0)
            {
                sprintf(line, "BGM %u/%u %s loop:%s", bgm_index + 1, BGM_COUNT, bgm_playing ? "PLAY" : "STOP", bgm_loop ? "ON" : "OFF");
                VDP_drawText(line, 1, 4);
                VDP_drawText(bgm_entries[bgm_index].label, 1, 5);
            }
            else VDP_drawText("BGM none", 1, 4);
            break;
    }
}

static void load_image(void)
{
    clear_scene();
    if (IMAGE_COUNT > 0 && image_entries[image_index].image)
    {
        if (image_entries[image_index].image->palette && image_entries[image_index].image->palette->data)
        {
            PAL_setPalette(PAL1, image_entries[image_index].image->palette->data, CPU);
        }
        VDP_drawImageEx(
            BG_B,
            image_entries[image_index].image,
            TILE_ATTR_FULL(PAL1, FALSE, FALSE, FALSE, TILE_BASE_INDEX),
            0,
            0,
            FALSE,
            DMA
        );
    }
    draw_header();
    draw_status();
    draw_footer();
}

static void load_sprite(void)
{
    clear_scene();
    draw_header();
    draw_status();
    draw_footer();
    SPR_init();
    if (SPRITE_COUNT > 0 && sprite_entries[sprite_index].sprite)
    {
        clamp_sprite_animation();
        if (sprite_entries[sprite_index].sprite->palette && sprite_entries[sprite_index].sprite->palette->data)
        {
            PAL_setPalette(PAL2, sprite_entries[sprite_index].sprite->palette->data, CPU);
        }
        current_sprite = SPR_addSprite(sprite_entries[sprite_index].sprite, 144, 108, TILE_ATTR(PAL2, FALSE, FALSE, FALSE));
        if (current_sprite)
        {
            SPR_setAnimationLoop(current_sprite, sprite_playing);
            SPR_setAnim(current_sprite, sprite_anim);
        }
    }
}

static void load_tilemap(void)
{
    clear_scene();
    draw_header();
    draw_status();
    draw_footer();
    tile_scroll_x = 0;
    tile_scroll_y = 0;

    if (TILEMAP_COUNT > 0 && tilemap_entries[tilemap_index].tilemap && tilemap_entries[tilemap_index].tileset)
    {
        if (tilemap_entries[tilemap_index].palette && tilemap_entries[tilemap_index].palette->data)
        {
            PAL_setPalette(PAL3, tilemap_entries[tilemap_index].palette->data, CPU);
        }
        VDP_loadTileSet(tilemap_entries[tilemap_index].tileset, TILE_BASE_INDEX, DMA);
        VDP_setTileMapEx(
            BG_B,
            tilemap_entries[tilemap_index].tilemap,
            TILE_ATTR_FULL(PAL3, FALSE, FALSE, FALSE, TILE_BASE_INDEX),
            0,
            8,
            0,
            0,
            40,
            20,
            CPU
        );
    }
    else if (TILEMAP_COUNT > 0)
    {
        VDP_drawText("TILEMAP needs tileset_id", 1, 10);
    }
}

static void load_bgm_status(void)
{
    clear_scene();
    if (bgm_playing && BGM_COUNT > 0) play_bgm();
    draw_header();
    draw_status();
    draw_footer();
}

static void refresh_category(void)
{
    switch (category)
    {
        case CATEGORY_IMAGE: load_image(); break;
        case CATEGORY_SPRITE: load_sprite(); break;
        case CATEGORY_TILEMAP: load_tilemap(); break;
        case CATEGORY_BGM: load_bgm_status(); break;
    }
}

static void move_selection(s16 delta)
{
    u16 count = count_for_category(category);
    u16* index = index_for_category(category);
    if (count == 0) return;
    if (delta > 0) *index = (u16)((*index + 1) % count);
    else *index = (u16)((*index + count - 1) % count);
    if (category == CATEGORY_SPRITE) sprite_anim = 0;
    if (category == CATEGORY_BGM && bgm_playing) play_bgm();
    refresh_category();
}

static void handle_a(void)
{
    if (category == CATEGORY_SPRITE && current_sprite)
    {
        sprite_playing = !sprite_playing;
        SPR_setAnimationLoop(current_sprite, sprite_playing);
        draw_status();
    }
    else if (category == CATEGORY_BGM && BGM_COUNT > 0)
    {
        if (bgm_playing) stop_bgm();
        else play_bgm();
        draw_status();
    }
}

static void handle_b(void)
{
    if (category == CATEGORY_SPRITE && current_sprite)
    {
        sprite_anim = (u16)((sprite_anim + 1) % sprite_animation_count());
        SPR_setAnim(current_sprite, sprite_anim);
        draw_status();
    }
    else if (category == CATEGORY_TILEMAP)
    {
        tile_scroll_dir = (u16)((tile_scroll_dir + 1) % 4);
        draw_status();
    }
    else if (category == CATEGORY_BGM)
    {
        bgm_loop = !bgm_loop;
        if (bgm_playing && BGM_COUNT > 0) play_bgm();
        draw_status();
    }
}

static void handle_c(void)
{
    if (category == CATEGORY_TILEMAP)
    {
        tile_scroll_speed = (tile_scroll_speed == 1) ? 2 : (tile_scroll_speed == 2) ? 4 : 1;
        draw_status();
    }
}

static void update_tilemap_scroll(void)
{
    if (category != CATEGORY_TILEMAP || TILEMAP_COUNT == 0) return;
    if (!tilemap_entries[tilemap_index].tilemap || !tilemap_entries[tilemap_index].tileset) return;

    switch (tile_scroll_dir)
    {
        case 0: tile_scroll_x -= (s16)tile_scroll_speed; break;
        case 1: tile_scroll_x += (s16)tile_scroll_speed; break;
        case 2: tile_scroll_y -= (s16)tile_scroll_speed; break;
        case 3: tile_scroll_y += (s16)tile_scroll_speed; break;
    }
    VDP_setHorizontalScroll(BG_B, tile_scroll_x);
    VDP_setVerticalScroll(BG_B, tile_scroll_y);
}

int main(bool hardReset)
{
    (void)hardReset;
    u16 prev = 0;

    VDP_setScreenWidth320();
    VDP_setPlaneSize(64, 32, TRUE);
    VDP_setScrollingMode(HSCROLL_PLANE, VSCROLL_PLANE);
    SPR_init();

    refresh_category();

    while (1)
    {
        u16 joy = JOY_readJoypad(JOY_1);
        u16 pressed = joy & ~prev;
        prev = joy;

        if (pressed & BUTTON_UP)
        {
            category = (Category)((category + UI_CATEGORY_COUNT - 1) % UI_CATEGORY_COUNT);
            refresh_category();
        }
        if (pressed & BUTTON_DOWN)
        {
            category = (Category)((category + 1) % UI_CATEGORY_COUNT);
            refresh_category();
        }
        if (pressed & BUTTON_LEFT) move_selection(-1);
        if (pressed & BUTTON_RIGHT) move_selection(1);
        if (pressed & BUTTON_A) handle_a();
        if (pressed & BUTTON_B) handle_b();
        if (pressed & BUTTON_C) handle_c();
        if (pressed & BUTTON_START)
        {
            show_help = !show_help;
            draw_footer();
        }

        update_tilemap_scroll();
        if (current_sprite) SPR_update();
        SYS_doVBlankProcess();
    }

    return 0;
}
