#!/usr/bin/env python3
"""Final Z80 bank register analysis for $FF0066 access"""

def main():
    print("=== Mega Drive Z80 Bank Register Analysis ===")
    print()
    print("Bank register: 9-bit shift register at Z80 address $6000")
    print("Each write: reg = (reg >> 1) | ((data & 1) << 8)")
    print("After 9 writes, bank value is complete")
    print("M68K address = bank_value << 15")
    print()
    
    print("=== GEMS Driver Bank Set Pattern ===")
    print()
    print("Variant 1 (at $0A21, $0A64, $0B96, $0C13):")
    print("  LD BC,$6000")
    print("  LD (BC),A  ; write A[0] -> becomes bank bit 0 after 8 more shifts")
    print("  RRCA       ; A >>= 1 rotate")
    print("  LD (BC),A  ; write A[1]")
    print("  RRCA")
    print("  ... (7 total LD (BC),A with RRCA)")
    print("  XOR A      ; A = 0")
    print("  LD (BC),A  ; write 0 -> bank bit 7")
    print("  LD (BC),A  ; write 0 -> bank bit 8")
    print()
    print("  Result: bank[6:0] = A[6:0], bank[8:7] = 0")
    print("  Max bank value: 127 (0x7F)")
    print("  Max M68K address: 0x%06X" % (127 << 15))
    print()
    
    print("Variant 2 (at $0284, VBlank handler):")
    print("  LD HL,$6000")
    print("  LD (HL),A  ; write A[0]")
    print("  RRCA")
    print("  ... (7 total LD (HL),A with RRCA)")
    print("  LD (HL),L  ; L=$00, write 0 -> bank bit 7")
    print("  LD (HL),L  ; write 0 -> bank bit 8")
    print()
    print("  Result: same as Variant 1")
    print("  Max bank value: 127 (0x7F)")
    print()
    
    print("=== Target Analysis ===")
    print()
    target = 0xFF0066
    bank_needed = target >> 15
    print("  M68K target: $%06X" % target)
    print("  Bank needed: %d (0x%03X)" % (bank_needed, bank_needed))
    print("  Bank binary:  %s" % format(bank_needed, '09b'))
    print("  Bit 8 of bank: %d" % ((bank_needed >> 8) & 1))
    print("  Bit 7 of bank: %d" % ((bank_needed >> 7) & 1))
    print()
    
    print("=== CONCLUSION ===")
    print()
    print("  The GEMS Z80 driver in this ROM CANNOT write to $FF0066.")
    print()
    print("  Reasons:")
    print("  1. All bank set routines force bits 7-8 to 0 (XOR A or LD (HL),L)")
    print("  2. Max reachable bank = 127, max M68K addr = $3F8000")
    print("  3. Bank 510 (0x1FE) is needed, requires bit 8 = 1")
    print("  4. No code in Z80 RAM writes a non-zero value for bits 7-8")
    print("  5. Bank write log confirms: only bank value 0 ever used (4158 writes)")
    print("  6. Banked read log is empty (no reads through bank window)")
    print()
    print("  The Z80 driver banks ONLY to ROM for reading sound data.")
    print("  Z80 <-> M68K communication is via Z80 RAM ($A00000-$A01FFF),")
    print("  not via bank-switched work RAM access.")
    print()
    print("  To write $FF0066, it must be done by the M68K CPU directly.")

if __name__ == "__main__":
    main()
