/* Generated by block-stage-exporter */
#ifndef _GAME_RESOURCES_H_
#define _GAME_RESOURCES_H_

#include "resources.h"

/* --- Sprite bindings --- */
#define RES_SPR_BALL spr_ball
#define RES_SPR_PADDLE spr_paddle
#define RES_SPR_POWERUP_MULTI_BALL spr_powerup_multi_ball
#define RES_SPR_POWERUP_STRONG spr_powerup_strong
#define RES_SPR_POWERUP_SPEED_UP spr_powerup_speed_up
#define RES_SPR_POWERUP_BARRIER spr_powerup_barrier
#define RES_SPR_BLOCK_WHITE spr_block_white
#define RES_SPR_BLOCK_YELLOW spr_block_yellow
#define RES_SPR_BLOCK_GREEN spr_block_green
#define RES_SPR_BLOCK_BLUE spr_block_blue
#define RES_SPR_BLOCK_GRAY spr_block_gray

/* --- Image bindings --- */
#define RES_IMG_LOGO_SCREEN_1 img_logo_screen_1
#define RES_IMG_LOGO_SCREEN_2 img_logo_screen_2
#define RES_IMG_TITLE_SCREEN img_title_screen
#define RES_IMG_GAME_OVER_SCREEN img_game_over_screen
#define RES_IMG_HIGH_SCORE_SCREEN img_high_score_screen
#define RES_IMG_GAME_CLEAR_SCREEN img_game_clear_screen

/* --- SE bindings --- */
#define RES_SE_BALL_HIT_PADDLE se_ball_hit_paddle
#define RES_SE_BALL_HIT_WALL se_ball_hit_wall
#define RES_SE_BLOCK_BREAK se_block_break
#define RES_SE_BLOCK_HIT se_ball_hit_wall
#define RES_SE_POWERUP_APPEAR se_powerup_appear
#define RES_SE_POWERUP_GET se_powerup_get
#define RES_SE_BALL_LOSE se_ball_lose
#define RES_SE_GAME_OVER se_game_over
#define RES_SE_STAGE_CLEAR se_stage_clear
#define RES_SE_BONUS_COUNT se_bonus_count
#define RES_SE_GAME_START se_game_start
#define RES_SE_PAUSE se_pause

/* --- BGM bindings --- */
#define RES_BGM_0 bgm_001
#define RES_BGM_1 bgm_004
#define RES_BGM_2 bgm_003
#define RES_BGM_3 bgm_002
#define RES_BGM_TITLE_SCREEN bgm_003
#define RES_BGM_TITLE_SCREEN_HALF_RATE TRUE
#define RES_BGM_GAME_CLEAR_SCREEN bgm_002
#define RES_BGM_GAME_CLEAR_SCREEN_HALF_RATE TRUE

#define BGM_IS_PCM 1

/* --- Font binding --- */
#define RES_SYSTEM_FONT font_system
#define RES_SYSTEM_FONT_PALETTE font_system_palette

/* --- Game settings --- */
#undef INITIAL_LIVES
#define INITIAL_LIVES 4
#undef BALL_BASE_SPEED
#define BALL_BASE_SPEED FIX16(3)
#undef PADDLE_SPEED
#define PADDLE_SPEED FIX16(3)
#undef BGM_VOLUME
#define BGM_VOLUME 100

/* --- Screen wait settings --- */
#undef SCREEN_WAIT_LOGO_SCREEN_1_SECONDS
#define SCREEN_WAIT_LOGO_SCREEN_1_SECONDS 3
#undef SCREEN_WAIT_LOGO_SCREEN_2_SECONDS
#define SCREEN_WAIT_LOGO_SCREEN_2_SECONDS 3
#undef SCREEN_WAIT_TITLE_SCREEN_SECONDS
#define SCREEN_WAIT_TITLE_SCREEN_SECONDS 55
#undef SCREEN_WAIT_HIGH_SCORE_SCREEN_SECONDS
#define SCREEN_WAIT_HIGH_SCORE_SCREEN_SECONDS 45
#undef SCREEN_WAIT_GAME_OVER_SCREEN_SECONDS
#define SCREEN_WAIT_GAME_OVER_SCREEN_SECONDS 0
#undef SCREEN_WAIT_GAME_CLEAR_SCREEN_SECONDS
#define SCREEN_WAIT_GAME_CLEAR_SCREEN_SECONDS 0

#endif /* _GAME_RESOURCES_H_ */
